apps/students/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import StudentInfoView, StudentScoreView, StudentIndexView

app_name = 'students'

urlpatterns = [
    # 学生站点首页
    url(r"^index/$", StudentIndexView.as_view(), name='student_index'),
    # 学生基本信息页
    url(r"^info/$", StudentInfoView.as_view(), name='student_info'),
    # 学生成绩列表
    url(r"^score/$", StudentScoreView.as_view(), name='student_score'),
]

wxcrm/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import xadmin
from django.views.static import serve

from .settings import STATIC_ROOT
from students.views import LogoutView, LoginView, RegisterView

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    # path('admin/', admin.site.urls),
    url(r'^$', LoginView.as_view(), name="login"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    # 学生相关操作
    url(r"^student/", include("students.urls", namespace='student')),
    # 老师相关操作
    url(r"^teacher/", include("teachers.urls", namespace='teacher')),
    # 配置验证码相关
    # url('captcha/', include('captcha.urls')),
    # 正式生产环境下，静态文件配置
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

apps/students/models.py
from __future__ import unicode_literals
# from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser

from teachers.models import TeacherInfo
from administrator.models import DormitoryInfo, ClassInfo, GradeInfo

# Create your models here.


class StudentInfo(models.Model):
    """学生基本信息表"""

    GENDER_CHOICE = (("male", "男"), ("female", "女"))
    ART_SCIENCE_CHOICES = (('art', '文科'), ('science', '理科'), ('all', '不分文理科'))

    file_number = models.IntegerField(primary_key=True, verbose_name='档案号', db_column='档案号')
    student_name = models.CharField(max_length=5, verbose_name="姓名", db_column='姓名', help_text='请输入您的真实姓名')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICE, verbose_name='性别', db_column='性别')
    ID = models.CharField(max_length=18,
                          verbose_name='身份证号',
                          db_column='身份证号',
                          help_text='请输入真实的身份证号',
                          error_messages={
                               'unique': '身份证号错误',
                               'max_length': '身份证最多十八位',
                          })
    password = models.CharField(max_length=16, verbose_name='密码', db_column='密码', help_text='请输入密码', default='xxxxxx')
    nation = models.CharField(max_length=10, verbose_name='民族', db_column='民族', default='汉族')
    teacher = models.ForeignKey(TeacherInfo, on_delete=models.SET_NULL, null=True, blank=True,
                                limit_choices_to={'is_class_leader': True},
                                verbose_name='班主任编号', db_column='班主任编号')  # 外键 筛选是班主任的老师
    year_join = models.CharField(max_length=4, verbose_name='入学年份', db_column='入学年份', help_text='请输入如：2018')
    grade = models.ForeignKey(GradeInfo, verbose_name='年级', on_delete=models.SET_NULL,
                              help_text='请保持您的入学年份上下相符',
                              null=True, db_column='年级', default='1')  # 外键
    clas = models.ForeignKey(ClassInfo, verbose_name='班级', on_delete=models.SET_NULL,
                             help_text='请保持您的入学年份上下相符',
                             null=True, db_column='班级', default='1')  # 外键
    dormitory_number = models.ForeignKey(DormitoryInfo, on_delete=models.SET_NULL, null=True,
                                         help_text='请保持您的入学年份上下相符',
                                         verbose_name='宿舍号', db_column='宿舍号')  # 外键
    bed_number = models.PositiveSmallIntegerField(verbose_name='床号', db_column='床号', default=0)
    art_science = models.CharField(max_length=7,
                                   verbose_name='文理科',
                                   db_column='文理科',
                                   choices=ART_SCIENCE_CHOICES,
                                   default='all')
    phone = models.CharField(max_length=11, verbose_name='电话', db_column='联系电话', help_text='请输入正确的联系方式',
                             error_messages={
                                 'max_length': '手机号最多十一位'
                             })
    address = models.TextField(max_length=100, verbose_name='地址', db_column='地址', default='', null=True, blank=True,
                               help_text='最多不超过一百个字',
                               error_messages={
                                   'max_length': '最多不超过一百个字',
                               })
    remark = models.TextField(max_length=100, verbose_name='备注', db_column='备注', default='', null=True, blank=True)

    class Meta:
        verbose_name = '学生信息表'
        verbose_name_plural = verbose_name
        db_table = '学生基本信息表'

    def save(self, *args, **kwargs):
        # 重写父类的save方法，并添加功能

        # 将学生登陆密码改为身份证后六位
        if self.password == 'xxxxxx':
            self.password = self.ID[-6:].lower()
        super(StudentInfo, self).save(*args, **kwargs)

    def __str__(self):
        return self.student_name

    def get_grade_class(self):
        return '{0}年级{1}'.format(self.gender, self.clas)
    get_grade_class.short_description = '班级年级'

    def get_all_score(self):
        return self.scoreinfo_set.all()
    get_all_score.short_description = '所有成绩'


class ExamList(models.Model):
    """考试列表"""

    id = models.IntegerField(verbose_name='考试序号', db_column='考试序号', help_text='如：1，表示第一次考试', primary_key=True)
    time = models.CharField(max_length=8, verbose_name='考试时间', db_column='考试时间',
                            help_text='如：20180512表示2018年5月12日', unique=True)
    remark = models.TextField(max_length=100, verbose_name='备注', db_column='备注', default='', null=True, blank=True)

    class Meta:
        verbose_name = '考试列表'
        verbose_name_plural = verbose_name
        db_table = '考试次序表'
        # ordering = ['-time']

    def __str__(self):
        time = self.time
        return '第{0}次考试，时间为{1}年{2}月{3}日'.format(self.id, time[:4], time[4:6], time[6:])

    def get_all_score(self):
        # 此次考试所有学生成绩
        return self.scoreinfo_set.all()
    get_all_score.short_description = '所有成绩'


class ScoreInfo(models.Model):
    """学生成绩详情表"""

    score_id = models.AutoField(verbose_name='成绩ID', db_column='成绩ID', primary_key=True)
    file_number = models.ForeignKey(StudentInfo, on_delete=models.SET_NULL, null=True,
                                    verbose_name='学生', db_column='学生')
    exam_number = models.CharField(max_length=10, verbose_name='准考证号', db_column='准考证号', default='xxxxxx')
    which_exam = models.ForeignKey(ExamList, on_delete=models.SET_NULL, null=True, verbose_name='考试', db_column='考试')

    # 各项成绩
    chinese = models.PositiveSmallIntegerField(verbose_name='语文', db_column='语文', default=0)
    math = models.PositiveSmallIntegerField(verbose_name='数学', db_column='数学', default=0)
    english = models.PositiveSmallIntegerField(verbose_name='英语', db_column='英语', default=0)
    physical = models.PositiveSmallIntegerField(verbose_name='物理', db_column='物理', default=0)
    chemistry = models.PositiveSmallIntegerField(verbose_name='化学', db_column='化学', default=0)
    biology = models.PositiveSmallIntegerField(verbose_name='生物', db_column='生物', default=0)
    politics = models.PositiveSmallIntegerField(verbose_name='政治', db_column='政治', default=0)
    geography = models.PositiveSmallIntegerField(verbose_name='地理', db_column='地理', default=0)
    history = models.PositiveSmallIntegerField(verbose_name='历史', db_column='历史', default=0)

    remark = models.TextField(max_length=100, verbose_name='备注', db_column='备注', blank=True, null=True)

    sum_score = models.PositiveSmallIntegerField(verbose_name='总分', db_column='总分', null=True, blank=True, default=0)
    grade_rank = models.PositiveSmallIntegerField(verbose_name='年级排名', db_column='年级排名', default=0)
    class_rank = models.PositiveSmallIntegerField(verbose_name='班级排名', db_column='班级排名', default=0)

    class Meta:
        verbose_name = '成绩列表'
        verbose_name_plural = verbose_name
        db_table = '具体成绩详情表'
        # unique_together = ['file_number', 'which_exam']
        # ordering = ['-which_exam', '-sum_score']

    def save(self, *args, **kwargs):
        # 覆盖save方法并增加功能

        # save方法中需要用到的变量
        exam_id = self.which_exam.id  # 确定本次考试的ID
        grade = self.file_number.grade  # 确定本次考试的年级
        clas = self.file_number.clas  # 确定年级

        # 如果当前成绩仍未默认值则更新总分字段
        # if self.sum_score == 0:
        subject = [self.chinese, self.math, self.english, self.physical, self.chemistry,
                   self.biology, self.politics, self.geography, self.history]
        total = sum(subject)

        # 如果排名仍为0则更新年级排名
        if self.grade_rank == 0:
            self.sum_score = total
            all_scores_grade_list = list(ScoreInfo.objects.filter(
                file_number__art_science__exact=self.file_number.art_science,
                which_exam__id=exam_id,
                file_number__grade__id=grade.id
            ).order_by('sum_score'))  # 将本次考试的所有成绩记录排序并列表化
            ordered_scores_grade_list = [i.sum_score for i in all_scores_grade_list]  # 获取所有的成绩

            from bisect import bisect_right, bisect_left  # 二分法
            # 用法
            # >>> bisect.bisect_right([1, 3, 3, 4], 3)
            # 3
            # >>> bisect.bisect_left([1, 3, 3, 4], 3)
            # 1
            insert_grade_position = bisect_right(ordered_scores_grade_list, self.sum_score)
            grade_rank = len(ordered_scores_grade_list) - insert_grade_position + 1
            self.grade_rank = grade_rank  # 更新当前成绩排名

            # 在更新排名之后，要将比分数小的记录排名加一
            need_score_grade_int = bisect_left(ordered_scores_grade_list, self.sum_score)  # 从need_score_int之后的成绩记录排名都需要加一
            need_scores_grade_list = all_scores_grade_list[:need_score_grade_int]  # 比当前成绩总分和大的成绩记录
            for score in need_scores_grade_list:
                score.grade_rank += 1  # 每一项记录的排名加一
                score.save()  # 保存修改
        else:
            if self.sum_score != total:
                # 数据库中总分与计算后的综合不相等，则说明是修改状态
                score_grade_queryset = ScoreInfo.objects.filter(
                    file_number__art_science__exact=self.file_number.art_science,
                    which_exam__id=exam_id,
                    file_number__grade__id=grade.id
                ).order_by('-sum_score')

                # 找出比total大的总分排序
                score_gt_grade_queryset = score_grade_queryset.filter(sum_score__gt=total)
                if self in score_gt_grade_queryset:
                    # 如果self在比当前总分大的查询set中，说明分数是降低的,去除本身
                    score_gt_grade_queryset = score_gt_grade_queryset.exclude(score_id__exact=self.score_id)

                if score_gt_grade_queryset.exists():
                    # 按照比自己分数大的记录数，排名+1
                    self.grade_rank = score_gt_grade_queryset.count() + 1
                else:
                    # 如果不存在总分比total大的成绩，则自己排名第一
                    self.grade_rank = 1

                if self.sum_score < total:
                    # 分数升高，则要将比自己原来分数高但又比total低的成绩排名降低，排名+1
                    for score in score_grade_queryset:

apps/students/forms.py
# -*- coding: utf-8 -*-
from django import forms
from captcha.fields import CaptchaField  # 验证码字段


class LoginForm(forms.Form):
    # 登录页面表单验证
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6, max_length=16,
                               error_messages={
                                   'max_length': '密码最多16位',
                                   'min_length': '密码不得少于6位',
                                   'required': '密码字段是不为空',
                               })


class RegisterForm(forms.Form):
    # 注册页面表单验证
    number = forms.IntegerField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})

apps/students/views.py
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect, HttpResponse
from django.views import View
from pure_pagination import Paginator, PageNotAnInteger

from .forms import LoginForm, RegisterForm
from .models import StudentInfo, ScoreInfo
from teachers.models import TeacherInfo
from utils.mixin_utils import LoginRequiredMixin

# Create your views here.


class LoginView(View):
    """用户登录页"""

    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):

        login_form = LoginForm(request.POST)  # form组件最前端数据进行校验
        if login_form.is_valid():
            # 如果表单验证成功，进行用户身份认证
            username = request.POST.get("username", "")
            password = request.POST.get("password", "")
            password = password.lower()
            character = request.POST.get("character")
            print(username, password, character, type(username), type(password), type(character))
            try:
                if isinstance(username, str):
                    username = int(username)

                # 判断登录用户的身份，1为学生， 2为老师
                if character == "2":
                    user = TeacherInfo.objects.get(number=username, password=password)
                    print(user)
                    red = HttpResponseRedirect(reverse('teacher:teacher_index'))  # 重定向到老师首页

                else:
                    user = StudentInfo.objects.get(file_number=username, password=password)
                    print(user)
                    red = HttpResponseRedirect(reverse('student:student_index'))  # 重定向到学生首页

                if user is not None:
                    # 若当前用户可用，则设置cookie和session值做认证
                    red.set_cookie('username', username, max_age=-1)
                    request.session['username'] = username
                    request.session['is_login'] = True
                    # request.session.set_expiry(0)
                    return red
                else:
                    # character 作为当老师认证登录失败的时候标识
                    return render(request, "login.html", {"msg": "用户名或者密码错误", 'character': character})
            except:
                return render(request, "login.html", {"msg": "用户名或者密码错误", 'character': character})
        else:
            return render(request, "login.html", {"msg": "用户名或者密码格式错误"})


class LogoutView(View):
    # 清除session
    def get(self, request):
        # 判断是否已经登录，在登录状态下清除session
        if not request.session.get('is_login', None):
            return redirect(reverse('login'))

        request.session.flush()
        return redirect(reverse('login'))


class RegisterView(View):
    def get(self, request):
        register_form = RegisterForm()
        return render(request, 'register.html', {'register_form': register_form})

    def post(self, request):
        # 实例化form对象，进行验证
        register_form = RegisterForm(request.POST)  # request.post包含从前台发送的表单
        # print('生成form')
        if register_form.is_valid():
            username = request.POST.get('number', '')
            if StudentInfo.objects.filter(file_number=username):
                return render(request, "register.html", {"msg": "用户已经存在", "register_form": register_form})
            password = request.POST.get('password', '')
            # print(username, password)
            user_profile = StudentInfo()
            user_profile.file_number = username
            user_profile.password = password
            user_profile.save()
            return render(request, "login.html")
        else:
            return render(request, "register.html", {"register_form": register_form})


class StudentIndexView(LoginRequiredMixin, View):
    # 学生站点首页

    def get(self, request):
        username = request.session.get('username')
        student = StudentInfo.objects.get(file_number=username)
        student_name = student.student_name
        context = {
            'title': '首页',
            'student': student,
            'student_name': student_name
        }
        return render(request, 'student/student_index.html', context=context)


class StudentInfoView(LoginRequiredMixin, View):
    # 学生基本信息页

    def get(self, request):
        username = request.session.get('username')
        student = StudentInfo.objects.get(file_number=username)
        student_name = student.student_name
        context = {
            'title': '基本信息',
            'student': student,
            'student_name': student_name,
        }
        return render(request, 'student/student_info.html', context=context)


class StudentScoreView(LoginRequiredMixin, View):
    # 学生成绩列表页

    def get(self, request):
        username = request.session.get('username')
        student = StudentInfo.objects.get(file_number=username)
        student_name = student.student_name
        score_list = ScoreInfo.objects.filter(file_number__file_number=student.file_number).order_by('-which_exam')
        score_list_count = len(score_list)

        # 分页功能
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        if request.GET.get('all') and score_list_count > 0:
            # 每一页显示几条数据
            page_count = score_list_count
        else:
            page_count = 1
        p = Paginator(score_list, page_count, request=request)
        score_list = p.page(page)

        context = {
            'title': '成绩详情页',
            'student': student,
            'score_list': score_list,
            'student_name': student_name,
            'score_list_count': score_list_count,
            'all': request.GET.get('all')
        }
        return render(request, 'student/student_score.html', context)

templates/student/student_index.html
{% extends 'student/left_content.html' %}

{% load  staticfiles %}

{% block title %}{{ title }}{% endblock title %}

{% block right_content %}
<div id="content-block" class="col-sm-11 col-md-10">
    <div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint" data-class-xs="navbar content-navbar navbar-inverse navbar-xs" data-class-sm="navbar content-navbar navbar-default navbar-xs">
        <div class="navbar-header">
            <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
                欢迎您 {{ student_name }}
            </a>
        </div>
    </div>
</div>
{% endblock right_content %}

templates/student/student_info.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en-us">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="robots" content="NONE,NOARCHIVE"/>
    <title>基本信息 | 温县第一高级中学后台管理</title>
    <link href="{% static 'css/bootstrap.css' %}" type="text/css" media="screen" rel="stylesheet">
    <link rel="stylesheet" type="text/css" id="site-theme" href="{% static 'css/bootstrap-xadmin.css' %}">
    <link href="{% static 'css/font-awesome.css' %}" type="text/css" media="screen" rel="stylesheet">
    <link href="{% static 'css/xadmin.main.css' %}" type="text/css" media="screen" rel="stylesheet">
    <link href="{% static 'css/xadmin.plugins.css' %}" type="text/css" media="screen" rel="stylesheet">
    <link href="{% static 'css/xadmin.responsive.css' %}" type="text/css" media="screen" rel="stylesheet">
    <link href="{% static 'css/xadmin.page.dashboard.css' %}" type="text/css" media="screen" rel="stylesheet">
    <link href="{% static 'css/xadmin.form.css' %}" type="text/css" media="screen" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
</head>
<body class="students-studentinfo change-form">

<!-- Header -->

    <div id="top-nav" class="navbar navbar-xs navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">温县第一高级中学后台管理</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">


                <li class="dropdown">
                    <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                        <strong>欢迎， {{ student_name }}</strong> </a>
                </li>

                <li><a href="{% url 'logout' %}"><i class="show-sm fa fa-sign-out"></i><span class="hide-sm">注销</span></a></li>
            </ul>


        </div>
    </div>

    <div id="body-content" class="clearfix row">

        <div id="left-side" class="col-sm-1 col-md-2">
        <div class="panel-group hide-sm nav-sitemenu col-md-2" id="nav-accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h6 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#nav-accordion" href="#nav-panel-1">
                        <i class="fa-fw fa fa-lock"></i>
                        个人中心
                        </a>
                    </h6>
                </div>

                <div id="nav-panel-1" class="list-group panel-collapse in" style="height: auto;">
                    <a href="{% url 'student:student_info' %}" class="list-group-item">
                        <i class="fa-fw fa fa-circle-o"></i>
                        &nbsp;基本信息
                    </a>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h6 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#nav-accordion" href="#nav-panel-2">
                        <i class="fa-fw fa fa-group"></i>
                        成绩信息
                        </a>
                    </h6>
                </div>
                <div id="nav-panel-2" class="list-group panel-collapse in" style="height: auto;">
                    <a href="{% url 'student:student_score' %}" class="list-group-item">
                        <i class="fa-fw fa fa-circle-o"></i>
                        &nbsp;成绩详情
                    </a>
                </div>
            </div>
        </div>
</div>

        <div id="content-block" class="col-sm-11 col-md-10">
            <ul class="breadcrumb">
                <li>
                    <a href="{% url 'students:student_index' %}">首页</a>
                </li>
                <li>
                    基本信息
                </li>

            </ul>


            <div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
                 data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
                 data-class-sm="navbar content-navbar navbar-default navbar-xs">
                <div class="navbar-header">
                    <a class="navbar-brand" data-toggle="collapse" data-target="#top-nav .navbar-collapse">
                        欢迎您：{{ student.student_name }}
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                    <div class="navbar-btn pull-right hide-xs">
                    </div>
                </div>
            </div>

            <form class="exform" enctype="multipart/form-data">
                <input type='hidden' id='_portal_key' value='students_studentinfo_editform_portal'/>
                <div class="form-container row clearfix">
                    <div id="column-0"
                         class="formColumn column form-column full col col-sm-12 form-horizontal" span="12" horizontal>
                        <div class="panel panel-default fieldset unsort no_title" id="box-0">
                            <div class="panel-heading"><i class='icon fa fa-chevron-up chevron'></i>
                                <h3 class="panel-title"></h3></div>
                            <div class="panel-body ">
                                <div id="div_file_number" class="value form-group row">
                                    <div class="control-label">档案号</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.file_number }}</p></div>
                                </div>
                                <div id="div_student_name" class="value form-group row">
                                    <div class="control-label">姓名</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.student_name }}</p></div>
                                </div>
                                <div id="div_ID" class="value form-group row">
                                    <div class="control-label">身份证号</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.ID }}</p></div>
                                </div>
                                <div id="div_gender" class="value form-group row">
                                    <div class="control-label">性别</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.get_gender_display }}</p></div>
                                </div>
                                <div id="div_password" class="value form-group row">
                                    <div class="control-label">密码</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.password }}</p></div>
                                </div>
                                <div id="div_phone" class="value form-group row">
                                    <div class="control-label">电话</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.phone }}</p></div>
                                </div>
                                <div id="div_teacher" class="value form-group row">
                                    <div class="control-label">班主任</div>
                                    <div class="controls"><p class="form-control-static "><span class="text-muted">{{ student.teacher }}</span>
                                    </p></div>
                                </div>
                                <div id="div_year_join" class="value form-group row">
                                    <div class="control-label">入学年份</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.year_join }}</p></div>
                                </div>
                                <div id="div_grade" class="value form-group row">
                                    <div class="control-label">年级</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.grade }}</p></div>
                                </div>
                                <div id="div_clas" class="value form-group row">
                                    <div class="control-label">班级</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.clas }}</p></div>
                                </div>
                                <div id="div_art_science" class="value form-group row">
                                    <div class="control-label">文理科</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.get_art_science_display }}</p></div>
                                </div>
                                <div id="div_nation" class="value form-group row">
                                    <div class="control-label">民族</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.nation }}</p></div>
                                </div>
                                <div id="div_dormitory_number" class="value form-group row">
                                    <div class="control-label">宿舍号</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.dormitory_number }}</p></div>
                                </div>
                                <div id="div_bed_number" class="value form-group row">
                                    <div class="control-label">床号</div>
                                    <div class="controls"><p class="form-control-static ">{{ student.bed_number }}</p></div>
                                </div>
                                <div id="div_address" class="value form-group row">
                                    <div class="control-label">地址</div>
                                    <div class="controls"><p class="form-control-static "><span class="text-muted">{{ student.address }}</span>
                                    </p></div>
                                </div>
                                <div id="div_remark" class="value form-group row">
                                    <div class="control-label">备注</div>
                                    <div class="controls"><p class="form-control-static "><span class="text-muted">{{ student.remark }}</span>
                                    </p></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </form>

        </div>
    </div>


    <div id="footer">
        <hr/>
        <footer class="text-center">
            <p>&copy; welcome to 温县第一高级中学后台管理 如果有问题请联系：XXXXXXXXXXX</p>
        </footer>
    </div>


    <script type="text/javascript" src="{% static 'js/jquery.ui.core.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.widget.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.mouse.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.sortable.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.responsive.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.effect.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.plugin.themes.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.page.dashboard.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.plugin.portal.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.sortable.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.effect.js' %}"></script>

</body>
</html>